name: Build and publish ApiMock

on:
    repository_dispatch:
        types: [release-published]

env:
    DOCKER_HUB_DOMAIN: "eumagnun"
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: teste
        run: echo ${{ github.event.client_payload.github.ref }}
         
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
             
      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::${github.event.client_payload.github.ref/refs\/tags\//}
        shell: bash 
        
      - uses: docker/setup-buildx-action@v1         
        
      - name: Build and push docker image for Open Banking Admin Api
        id: docker_build_admin_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./documentation/mock/swagger_admin_apis/Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/admin-api:${{ steps.get_version.outputs.VERSION }}
          push: true
        
      - name: Build and push docker image for Open Banking Channels Api
        id: docker_build_channels_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./documentation/mock/swagger_channels_apis/Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/channels-api:${{ steps.get_version.outputs.VERSION }}
          push: true
        
      - name: Build and push docker image for Open Banking Common Api
        id: docker_build_common_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./documentation/mock/swagger_common_apis/Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/common-api:${{ steps.get_version.outputs.VERSION }}
          push: true
        
      - name: Build and push docker image for Open Banking Products Services Api
        id: docker_build_products_services_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./documentation/mock/swagger_products_services_apis/Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/products-services-api:${{ steps.get_version.outputs.VERSION }}
          push: true
