name: Build and publish ApiMock

on:
    repository_dispatch:
        types: [release-published]

env:
    DOCKER_HUB_DOMAIN: "eumagnun"
    GITHUB_DOMAIN: "https://github.com/eumagnun"  

    ADMIN_API_SWAGGER: ${{env.GITHUB_DOMAIN}}"/areadesenvolvedor/blob/{0}/documentation/source/swagger/swagger_admin_apis.yaml"
    ADMIN_API_PORT: "7001"

    CHANNELS_API_SWAGGER: "https://github.com/eumagnun/areadesenvolvedor/blob/{0}/documentation/source/swagger/swagger_channels_apis.yaml"
    CHANNELS_API_PORT: "7002"

    COMMON_API_SWAGGER: "https://github.com/eumagnun/areadesenvolvedor/blob/{0}/documentation/source/swagger/swagger_common_apis.yaml"
    COMMON_API_PORT: "7003"

    PRODUCTS_SERVICES_API_SWAGGER: "https://github.com/eumagnun/areadesenvolvedor/blob/{0}/documentation/source/swagger/swagger_products_services_apis.yaml"
    PRODUCTS_SERVICES_API_PORT: "7004"
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: teste
        run: echo ${{ github.event.client_payload.repository }} || ${{ github.event.client_payload.branch }} || ${{ github.event.client_payload.tagName }}
         
         
      - name: Checkout openbanking repo
        uses: actions/checkout@master
        with:
          repository: eumagnun/areadesenvolvedor

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
                
      - uses: docker/setup-buildx-action@v1         
        
      - name: Build and push docker image for Open Banking Admin Api
        id: docker_build_admin_api
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/admin-api:${{ github.event.client_payload.tagName }}
          build-args: |
            api_swagger_name=format( ${{ env.ADMIN_API_SWAGGER }}, github.event.client_payload.tagName
            api_port=${{ env.ADMIN_API_PORT }}
          push: true
      
